apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: mooomoocat-es
  namespace: mooomoocat-rag
  labels:
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/part-of: mooomoocat-rag-deps
spec:
  version: 9.2.3
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false
      podTemplate:
        metadata:
          labels:
            app.kubernetes.io/part-of: mooomoocat-rag-deps
        spec:
          containers:
            - name: elasticsearch
              env:
                - name: ES_JAVA_OPTS
                  value: -Xms512m -Xmx512m
              resources:
                requests:
                  cpu: 500m
                  memory: 1Gi
                limits:
                  memory: 1Gi
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
